/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImprimirRouteImport } from './routes/imprimir'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as GeradorIntermediariaRouteImport } from './routes/gerador-intermediaria'
import { Route as GeradorRouteImport } from './routes/gerador'
import { Route as CodigosRouteImport } from './routes/codigos'
import { Route as IndexRouteImport } from './routes/index'

const ImprimirRoute = ImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorIntermediariaRoute = GeradorIntermediariaRouteImport.update({
  id: '/gerador-intermediaria',
  path: '/gerador-intermediaria',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorRoute = GeradorRouteImport.update({
  id: '/gerador',
  path: '/gerador',
  getParentRoute: () => rootRouteImport,
} as any)
const CodigosRoute = CodigosRouteImport.update({
  id: '/codigos',
  path: '/codigos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codigos': typeof CodigosRoute
  '/gerador': typeof GeradorRoute
  '/gerador-intermediaria': typeof GeradorIntermediariaRoute
  '/historico': typeof HistoricoRoute
  '/imprimir': typeof ImprimirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codigos': typeof CodigosRoute
  '/gerador': typeof GeradorRoute
  '/gerador-intermediaria': typeof GeradorIntermediariaRoute
  '/historico': typeof HistoricoRoute
  '/imprimir': typeof ImprimirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codigos': typeof CodigosRoute
  '/gerador': typeof GeradorRoute
  '/gerador-intermediaria': typeof GeradorIntermediariaRoute
  '/historico': typeof HistoricoRoute
  '/imprimir': typeof ImprimirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/codigos' | '/gerador' | '/gerador-intermediaria' | '/historico' | '/imprimir'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/codigos' | '/gerador' | '/gerador-intermediaria' | '/historico' | '/imprimir'
  id: '__root__' | '/' | '/codigos' | '/gerador' | '/gerador-intermediaria' | '/historico' | '/imprimir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodigosRoute: typeof CodigosRoute
  GeradorRoute: typeof GeradorRoute
  GeradorIntermediariaRoute: typeof GeradorIntermediariaRoute
  HistoricoRoute: typeof HistoricoRoute
  ImprimirRoute: typeof ImprimirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/imprimir': {
      id: '/imprimir'
      path: '/imprimir'
      fullPath: '/imprimir'
      preLoaderRoute: typeof ImprimirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador-intermediaria': {
      id: '/gerador-intermediaria'
      path: '/gerador-intermediaria'
      fullPath: '/gerador-intermediaria'
      preLoaderRoute: typeof GeradorIntermediariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador': {
      id: '/gerador'
      path: '/gerador'
      fullPath: '/gerador'
      preLoaderRoute: typeof GeradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigos': {
      id: '/codigos'
      path: '/codigos'
      fullPath: '/codigos'
      preLoaderRoute: typeof CodigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodigosRoute: CodigosRoute,
  GeradorRoute: GeradorRoute,
  GeradorIntermediariaRoute: GeradorIntermediariaRoute,
  HistoricoRoute: HistoricoRoute,
  ImprimirRoute: ImprimirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
