/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as ImprimirRouteImport } from './routes/imprimir'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as GeradorIntermediariaRouteImport } from './routes/gerador-intermediaria'
import { Route as GeradorHistoricoRouteImport } from './routes/gerador-historico'
import { Route as GeradorRouteImport } from './routes/gerador'
import { Route as CodigosRouteImport } from './routes/codigos'
import { Route as CertidoesRouteImport } from './routes/certidoes'
import { Route as IndexRouteImport } from './routes/index'

const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprimirRoute = ImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorIntermediariaRoute = GeradorIntermediariaRouteImport.update({
  id: '/gerador-intermediaria',
  path: '/gerador-intermediaria',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorHistoricoRoute = GeradorHistoricoRouteImport.update({
  id: '/gerador-historico',
  path: '/gerador-historico',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorRoute = GeradorRouteImport.update({
  id: '/gerador',
  path: '/gerador',
  getParentRoute: () => rootRouteImport,
} as any)
const CodigosRoute = CodigosRouteImport.update({
  id: '/codigos',
  path: '/codigos',
  getParentRoute: () => rootRouteImport,
} as any)
const CertidoesRoute = CertidoesRouteImport.update({
  id: '/certidoes',
  path: '/certidoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certidoes': typeof CertidoesRoute
  '/codigos': typeof CodigosRoute
  '/gerador': typeof GeradorRoute
  '/gerador-historico': typeof GeradorHistoricoRoute
  '/gerador-intermediaria': typeof GeradorIntermediariaRoute
  '/historico': typeof HistoricoRoute
  '/imprimir': typeof ImprimirRoute
  '/mapa': typeof MapaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certidoes': typeof CertidoesRoute
  '/codigos': typeof CodigosRoute
  '/gerador': typeof GeradorRoute
  '/gerador-historico': typeof GeradorHistoricoRoute
  '/gerador-intermediaria': typeof GeradorIntermediariaRoute
  '/historico': typeof HistoricoRoute
  '/imprimir': typeof ImprimirRoute
  '/mapa': typeof MapaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certidoes': typeof CertidoesRoute
  '/codigos': typeof CodigosRoute
  '/gerador': typeof GeradorRoute
  '/gerador-historico': typeof GeradorHistoricoRoute
  '/gerador-intermediaria': typeof GeradorIntermediariaRoute
  '/historico': typeof HistoricoRoute
  '/imprimir': typeof ImprimirRoute
  '/mapa': typeof MapaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certidoes'
    | '/codigos'
    | '/gerador'
    | '/gerador-historico'
    | '/gerador-intermediaria'
    | '/historico'
    | '/imprimir'
    | '/mapa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certidoes'
    | '/codigos'
    | '/gerador'
    | '/gerador-historico'
    | '/gerador-intermediaria'
    | '/historico'
    | '/imprimir'
    | '/mapa'
  id:
    | '__root__'
    | '/'
    | '/certidoes'
    | '/codigos'
    | '/gerador'
    | '/gerador-historico'
    | '/gerador-intermediaria'
    | '/historico'
    | '/imprimir'
    | '/mapa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertidoesRoute: typeof CertidoesRoute
  CodigosRoute: typeof CodigosRoute
  GeradorRoute: typeof GeradorRoute
  GeradorHistoricoRoute: typeof GeradorHistoricoRoute
  GeradorIntermediariaRoute: typeof GeradorIntermediariaRoute
  HistoricoRoute: typeof HistoricoRoute
  ImprimirRoute: typeof ImprimirRoute
  MapaRoute: typeof MapaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprimir': {
      id: '/imprimir'
      path: '/imprimir'
      fullPath: '/imprimir'
      preLoaderRoute: typeof ImprimirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador-intermediaria': {
      id: '/gerador-intermediaria'
      path: '/gerador-intermediaria'
      fullPath: '/gerador-intermediaria'
      preLoaderRoute: typeof GeradorIntermediariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador-historico': {
      id: '/gerador-historico'
      path: '/gerador-historico'
      fullPath: '/gerador-historico'
      preLoaderRoute: typeof GeradorHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador': {
      id: '/gerador'
      path: '/gerador'
      fullPath: '/gerador'
      preLoaderRoute: typeof GeradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigos': {
      id: '/codigos'
      path: '/codigos'
      fullPath: '/codigos'
      preLoaderRoute: typeof CodigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certidoes': {
      id: '/certidoes'
      path: '/certidoes'
      fullPath: '/certidoes'
      preLoaderRoute: typeof CertidoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertidoesRoute: CertidoesRoute,
  CodigosRoute: CodigosRoute,
  GeradorRoute: GeradorRoute,
  GeradorHistoricoRoute: GeradorHistoricoRoute,
  GeradorIntermediariaRoute: GeradorIntermediariaRoute,
  HistoricoRoute: HistoricoRoute,
  ImprimirRoute: ImprimirRoute,
  MapaRoute: MapaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
